import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
)

function buildResumeLocally(data: any): string {
  const {
    name, email, phone, skills,
    experience, education, projects,
    targetRole, targetCompany
  } = data

  return `
${name.toUpperCase()}
${email} | ${phone}
Target Role: ${targetRole} ${targetCompany ? `at ${targetCompany}` : ''}

─────────────────────────────────────────
PROFESSIONAL SUMMARY
─────────────────────────────────────────
A motivated and passionate ${targetRole} with strong technical skills and 
a drive to deliver quality work. Eager to contribute to ${targetCompany || 'a great organization'} 
and grow professionally in a dynamic environment.

─────────────────────────────────────────
SKILLS
─────────────────────────────────────────
${skills}

─────────────────────────────────────────
WORK EXPERIENCE
─────────────────────────────────────────
${experience || 'Fresher — No prior work experience.\nReady to learn and contribute from Day 1.'}

─────────────────────────────────────────
EDUCATION
─────────────────────────────────────────
${education || 'Please add your education details.'}

─────────────────────────────────────────
PROJECTS
─────────────────────────────────────────
${projects || 'Please add your project details.'}

─────────────────────────────────────────
NOTE: This resume was generated by AI Placement Coach.
Add your Claude API key to get a fully AI-optimized resume.
─────────────────────────────────────────
`.trim()
}

export async function POST(req: NextRequest) {
  try {
    const body = await req.json()
    const {
      userId, name, email, phone,
      skills, experience, education,
      projects, targetRole, targetCompany
    } = body

    if (!userId || !name || !skills || !targetRole) {
      return NextResponse.json(
        { error: 'Please fill Name, Skills and Target Role.' },
        { status: 400 }
      )
    }

    // Check credits
    const { data: sub } = await supabase
      .from('subscriptions')
      .select('credits_remaining')
      .eq('user_id', userId)
      .single()

    if (!sub || sub.credits_remaining < 5) {
      return NextResponse.json(
        { error: 'Not enough credits. You need 5 credits.' },
        { status: 402 }
      )
    }

    // Deduct 5 credits
    await supabase
      .from('subscriptions')
      .update({ credits_remaining: sub.credits_remaining - 5 })
      .eq('user_id', userId)

    // Generate resume
    let resumeContent = ''

    // Try Claude API if key exists
    if (process.env.ANTHROPIC_API_KEY &&
        process.env.ANTHROPIC_API_KEY !== 'add_later') {
      try {
        const Anthropic = (await import('@anthropic-ai/sdk')).default
        const client = new Anthropic({
          apiKey: process.env.ANTHROPIC_API_KEY
        })
        const prompt = `
You are an expert resume writer for the Indian job market.
Create a professional ATS-friendly resume.

Name: ${name}
Email: ${email}
Phone: ${phone}
Skills: ${skills}
Experience: ${experience}
Education: ${education}
Projects: ${projects}
Target Role: ${targetRole}
Target Company: ${targetCompany}

Instructions:
- Use strong action verbs
- Quantify achievements where possible
- Keep to 1 page
- Sections: SUMMARY, SKILLS, EXPERIENCE, EDUCATION, PROJECTS
- Optimize for Naukri and LinkedIn ATS
- Tailor for ${targetCompany || 'Indian companies'}

Return only the resume text, no extra explanation.
`
        const response = await client.messages.create({
          model: 'claude-sonnet-4-20250514',
          max_tokens: 2000,
          messages: [{ role: 'user', content: prompt }]
        })
        resumeContent = response.content[0].type === 'text'
          ? response.content[0].text : ''
      } catch (err) {
        console.log('Claude API failed, using local builder:', err)
        resumeContent = buildResumeLocally(body)
      }
    } else {
      resumeContent = buildResumeLocally(body)
    }

    // Save to Supabase
    const { data, error } = await supabase
      .from('resumes')
      .insert({
        user_id: userId,
        job_role: targetRole,
        target_company: targetCompany,
        resume_content: resumeContent,
        ats_score: 0
      })
      .select()
      .single()

    if (error) console.error('Supabase error:', error)

    return NextResponse.json({
      success: true,
      resume: resumeContent,
      resumeId: data?.id
    })

  } catch (error) {
    console.error('Resume error:', error)
    return NextResponse.json(
      { error: 'Failed to generate resume. Please try again.' },
      { status: 500 }
    )
  }
}

export async function GET(req: NextRequest) {
  try {
    const userId = req.nextUrl.searchParams.get('userId')
    if (!userId) {
      return NextResponse.json({ error: 'Missing userId' }, { status: 400 })
    }

    const { data, error } = await supabase
      .from('resumes')
      .select('*')
      .eq('user_id', userId)
      .order('created_at', { ascending: false })

    if (error) throw error
    return NextResponse.json({ resumes: data })

  } catch (error) {
    return NextResponse.json(
      { error: 'Failed to fetch resumes' },
      { status: 500 }
    )
  }
}